event_inherited();
alpha = 1;
image_speed = 1;
image_index = 0;
_image_speed = 1;
_image_index = 0;
angle = 0;
check = 0;
distance = 0;
bounceFrom = -1;
bounceToX = x;
bounceToY = room_height - 20;
bounceFromX = x;
bounceFromY = room_height - 20;
bounceToH = room_height - 20;
bounceFromH = room_height - 20;
frequency = room_speed / 5;
gml_Script_scr_playsound(s_spark2, 0.9, 1.1, 0.2);
sprite = spr_thunderAnimation;
alarm[0] = frequency;
alarm[1] = room_speed * 10;
