global.light_partsys = part_system_create();
part_system_depth(global.light_partsys, -10);
part_system_automatic_draw(global.light_partsys, false);
global.floor_partsys = part_system_create();
part_system_depth(global.floor_partsys, 5);
global.over_partsys = part_system_create_layer("Compatibility_Instances_Depth_-103", true);
global.snow_partsys = part_system_create_layer("Compatibility_Instances_Depth_-103", true);
global.blizzard_partsys = part_system_create_layer("Compatibility_Instances_Depth_-103", true);
global.smokebomb_partsys = part_system_create_layer("Compatibility_Instances_Depth_-103", true);
global.fire_partsys = part_system_create_layer("Compatibility_Instances_Depth_-103", true, partsys_fire);
global.raidObject_partsys = part_system_create_layer("Compatibility_Instances_Depth_-101", true);
part_system_depth(global.raidObject_partsys, 5);
part_system_automatic_draw(global.over_partsys, false);
part_system_automatic_draw(global.fire_partsys, false);
part_system_automatic_draw(global.blizzard_partsys, false);
part_system_automatic_draw(global.snow_partsys, false);
part_system_automatic_draw(global.smokebomb_partsys, false);
part_system_automatic_draw(global.raidObject_partsys, false);
global.fire_partemit = part_emitter_create(global.fire_partsys);
global.light_part1 = part_type_create();
part_type_sprite(global.light_part1, spr_part_glow, 0, 0, 0);
part_type_orientation(global.light_part1, 0, 359, 0.01, 0.05, 0);
part_type_size(global.light_part1, 0.1, 0.15, 0, 0);
part_type_alpha2(global.light_part1, 1, 0);
part_type_color2(global.light_part1, 65535, 4235519);
part_type_direction(global.light_part1, 80, 100, 0, 0);
part_type_life(global.light_part1, room_speed / 1.5, room_speed);
part_type_gravity(global.light_part1, -0.002, 270);
global.light_partemitter = part_emitter_create(global.light_partsys);
global.level_part1 = part_type_create();
part_type_sprite(global.level_part1, spr_xp_part, 0, 0, 0);
part_type_size(global.level_part1, 0.5, 1.5, 0, 0);
part_type_speed(global.level_part1, 1, 2, 0, 0);
part_type_alpha2(global.level_part1, 1, 0.2);
part_type_direction(global.level_part1, 90, 90, 0, 0);
part_type_life(global.level_part1, room_speed / 2, room_speed);
part_type_gravity(global.level_part1, 0.002, 270);
global.level_partemitter = part_emitter_create(global.light_partsys);
global.rainpart = part_type_create();
part_type_shape(global.rainpart, 3);
part_type_size(global.rainpart, 0.08, 0.13, 0, 0);
part_type_color2(global.rainpart, 128, 255);
part_type_scale(global.rainpart, 3, 3);
part_type_alpha2(global.rainpart, 0.8, 0.1);
part_type_gravity(global.rainpart, 0.05, 270);
part_type_speed(global.rainpart, 16, 16, 0, 0);
part_type_direction(global.rainpart, 270, 280, 0, 1);
part_type_orientation(global.rainpart, 275, 275, 0, 0, 0);
part_type_life(global.rainpart, 15, 16);
global.raindroppart = part_type_create();
part_type_sprite(global.raindroppart, spr_rain2, 0, 0, 0);
part_type_size(global.raindroppart, 1, 1, 0.01, 0);
part_type_color1(global.raindroppart, 255);
part_type_alpha2(global.raindroppart, 0.8, 0);
part_type_speed(global.raindroppart, 0, 0, 0, 0);
part_type_direction(global.raindroppart, 0, 0, 0, 0);
part_type_life(global.raindroppart, 20, 40);
part_type_gravity(global.raindroppart, 0, 270);
global.raindroppart2 = part_type_create();
part_type_sprite(global.raindroppart2, spr_rain1, 0, 0, 0);
part_type_size(global.raindroppart2, 1, 2, 0, 0);
part_type_color1(global.raindroppart2, 255);
part_type_alpha2(global.raindroppart2, 0.8, 0.4);
part_type_speed(global.raindroppart2, 1, 1.5, 0, 0);
part_type_direction(global.raindroppart2, 30, 150, 0, 0);
part_type_life(global.raindroppart2, 5, 10);
part_type_gravity(global.raindroppart2, 0.1, 270);
part_type_death(global.rainpart, random_range(2, 3), global.raindroppart2);
global.rainpart_emitter = part_emitter_create(global.light_partsys);
global.deathrainpart_emitter = part_emitter_create(global.over_partsys);
global.rainpart2 = part_type_create();
part_type_shape(global.rainpart2, 3);
part_type_size(global.rainpart2, 0.16, 0.26, 0, 0);
part_type_color2(global.rainpart2, 8388736, 16711935);
part_type_scale(global.rainpart2, 1, 1);
part_type_alpha2(global.rainpart2, 0.8, 0.4);
part_type_gravity(global.rainpart2, 0.05, 270);
part_type_speed(global.rainpart2, 16.7, 16.8, 0, 0);
part_type_direction(global.rainpart2, 270, 280, 0, 1);
part_type_orientation(global.rainpart2, 275, 275, 0, 0, 0);
part_type_life(global.rainpart2, 10, 50);
global.raindroppart3 = part_type_create();
part_type_sprite(global.raindroppart3, spr_rain2, 0, 0, 0);
part_type_size(global.raindroppart3, 0.75, 0.75, 0.01, 0);
part_type_color1(global.raindroppart3, 16711935);
part_type_alpha2(global.raindroppart3, 0.8, 0);
part_type_speed(global.raindroppart3, 0, 0, 0, 0);
part_type_direction(global.raindroppart3, 0, 0, 0, 0);
part_type_life(global.raindroppart3, 20, 30);
part_type_gravity(global.raindroppart3, 0, 270);
global.raindroppart4 = part_type_create();
part_type_sprite(global.raindroppart4, spr_rain1, 0, 0, 0);
part_type_scale(global.raindroppart4, 0.5, 0.5);
part_type_color1(global.raindroppart4, 16711935);
part_type_alpha2(global.raindroppart4, 0.8, 0.4);
part_type_speed(global.raindroppart4, 1, 2, 0, 0);
part_type_direction(global.raindroppart4, 30, 150, 0, 0);
part_type_life(global.raindroppart4, 10, 20);
part_type_gravity(global.raindroppart4, 0.1, 270);
part_type_death(global.rainpart2, 1, global.raindroppart3);
part_type_death(global.raindroppart3, random_range(2, 5), global.raindroppart4);
global.rainpart_emitter2 = part_emitter_create(global.light_partsys);
global.aura_part = part_type_create();
part_type_sprite(global.aura_part, spr_part_aura, 0, 0, 0);
part_type_orientation(global.aura_part, 0, 359, 0.01, 0.05, 0);
part_type_size(global.aura_part, 0.2, 0.3, 0, 0);
part_type_alpha3(global.aura_part, 0, 1, 0);
part_type_color2(global.aura_part, 65535, 4235519);
part_type_direction(global.aura_part, 80, 100, 0, 0);
part_type_life(global.aura_part, room_speed * 1.5, room_speed * 3);
part_type_gravity(global.aura_part, -0.01, 270);
global.aura_partemitter = part_emitter_create(global.light_partsys);
global.aura_part_red = part_type_create();
part_type_sprite(global.aura_part_red, spr_part_aura, 0, 0, 0);
part_type_orientation(global.aura_part_red, 0, 359, 0.01, 0.05, 0);
part_type_size(global.aura_part_red, 0.4, 0.6, 0, 0);
part_type_alpha3(global.aura_part_red, 0, 1, 0);
part_type_color2(global.aura_part_red, 255, 128);
part_type_direction(global.aura_part_red, 80, 100, 0, 0);
part_type_life(global.aura_part_red, room_speed * 1.5, room_speed * 3);
part_type_gravity(global.aura_part_red, -0.01, 270);
global.auraBig_part = part_type_create();
part_type_sprite(global.auraBig_part, spr_part_aura, 0, 0, 0);
part_type_orientation(global.auraBig_part, 0, 359, 0.01, 0.05, 0);
part_type_size(global.auraBig_part, 0.4, 0.6, 0, 0);
part_type_alpha3(global.auraBig_part, 0, 1, 0);
part_type_color2(global.auraBig_part, 65535, 4235519);
part_type_direction(global.auraBig_part, 80, 100, 0, 0);
part_type_life(global.auraBig_part, room_speed * 1.5, room_speed * 3);
part_type_gravity(global.auraBig_part, -0.01, 270);
global.blizzard_part = part_type_create();
part_type_sprite(global.blizzard_part, spr_part_glow, 0, 0, 0);
part_type_scale(global.blizzard_part, 0.3, 0.3);
part_type_size(global.blizzard_part, 0.4, 0.7, 0, 0.02);
part_type_speed(global.blizzard_part, 8, 10, 0, 0);
part_type_alpha3(global.blizzard_part, 0, 0.8, 0);
part_type_color_rgb(global.blizzard_part, 209, 209, 243, 243, 255, 255);
part_type_direction(global.blizzard_part, 310, 340, 0, 5);
part_type_life(global.blizzard_part, room_speed / 2, room_speed * 2);
global.blizzard_partemitter = part_emitter_create(global.snow_partsys);
global.poison_part = part_type_create();
part_type_shape(global.poison_part, 6);
part_type_scale(global.poison_part, 0.3, 0.3);
part_type_size(global.poison_part, 0.5, 0.8, 0, 0.02);
part_type_speed(global.poison_part, 0.5, 1, 0, 0.1);
part_type_alpha3(global.poison_part, 0, 0.7, 0.5);
part_type_color_rgb(global.poison_part, 50, 150, 100, 150, 20, 40);
part_type_direction(global.poison_part, 70, 110, 0, 5);
part_type_life(global.poison_part, 0, room_speed);
global.poison_partemitter = part_emitter_create(global.over_partsys);
global.poisonbomb_part = part_type_create();
part_type_shape(global.poisonbomb_part, 11);
part_type_orientation(global.poisonbomb_part, 0, 359, 0, 0, 0);
part_type_scale(global.poisonbomb_part, 3, 3);
part_type_size(global.poisonbomb_part, 0.4, 0.7, 0, 0.02);
part_type_speed(global.poisonbomb_part, 1, 2, 0, 0.1);
part_type_alpha3(global.poisonbomb_part, 0.5, 0.9, 0.2);
part_type_color_rgb(global.poisonbomb_part, 50, 150, 100, 150, 20, 40);
part_type_direction(global.poisonbomb_part, 0, 180, 0, 1);
part_type_life(global.poisonbomb_part, room_speed, room_speed * 2);
global.poisonbomb_partemitter = part_emitter_create(global.smokebomb_partsys);
global.smokebomb_part = part_type_create();
part_type_shape(global.smokebomb_part, 11);
part_type_orientation(global.smokebomb_part, 0, 359, 0, 0, 0);
part_type_scale(global.smokebomb_part, 4, 4);
part_type_size(global.smokebomb_part, 0.4, 0.7, 0, 0.02);
part_type_speed(global.smokebomb_part, 0.6, 1, 0, 0.02);
part_type_alpha3(global.smokebomb_part, 0.3, 0.8, 0);
part_type_color1(global.smokebomb_part, 8421504);
part_type_direction(global.smokebomb_part, 0, 180, 0, 1);
part_type_life(global.smokebomb_part, room_speed / 2, room_speed);
global.smokebomb_partemitter = part_emitter_create(global.smokebomb_partsys);
global.blizzardSmoke_part = part_type_create();
part_type_shape(global.blizzardSmoke_part, 11);
part_type_orientation(global.blizzardSmoke_part, 0, 359, 0, 0, 0);
part_type_scale(global.blizzardSmoke_part, 3, 3);
part_type_size(global.blizzardSmoke_part, 0.4, 0.7, 0.01, 0);
part_type_speed(global.blizzardSmoke_part, 1, 2, 0, 0.1);
part_type_alpha3(global.blizzardSmoke_part, 0, 0.1, 0);
part_type_color1(global.blizzardSmoke_part, 16777215);
part_type_direction(global.blizzardSmoke_part, 0, 180, 0, 0);
part_type_life(global.blizzardSmoke_part, room_speed * 2, room_speed * 4);
part_type_blend(global.blizzardSmoke_part, false);
global.blizzardSmoke_partemitter = part_emitter_create(global.blizzard_partsys);
global.burn_part = part_type_create();
part_type_shape(global.burn_part, 10);
part_type_orientation(global.burn_part, 0, 359, 0, 0, 0);
part_type_scale(global.burn_part, 0.6, 0.6);
part_type_size(global.burn_part, 0.4, 0.7, -0.01, 0.02);
part_type_speed(global.burn_part, 1, 2, 0, 0.5);
part_type_alpha3(global.burn_part, 0.5, 0.8, 0.2);
part_type_color3(global.burn_part, 4235519, 255, 4210752);
part_type_direction(global.burn_part, 80, 100, 0, 5);
part_type_life(global.burn_part, room_speed / 1.5, room_speed);
part_type_blend(global.burn_part, true);
global.burn_partemitter = part_emitter_create(global.over_partsys);
global.firesmoke_part = part_type_create();
part_type_shape(global.firesmoke_part, 11);
part_type_orientation(global.firesmoke_part, 0, 359, 0, 0, 0);
part_type_scale(global.firesmoke_part, 1, 1);
part_type_size(global.firesmoke_part, 0.4, 0.7, 0.05, 0.02);
part_type_speed(global.firesmoke_part, 1, 2, 0, 0.5);
part_type_alpha3(global.firesmoke_part, 1, 0.8, 0.5);
part_type_color3(global.firesmoke_part, 4235519, 8421504, 4210752);
part_type_direction(global.firesmoke_part, 80, 100, 0, 5);
part_type_life(global.firesmoke_part, room_speed / 1.5, room_speed);
part_type_blend(global.firesmoke_part, false);
global.burn_partemitter = part_emitter_create(global.over_partsys);
global.ember_part = part_type_create();
part_type_shape(global.ember_part, 0);
part_type_scale(global.ember_part, 4, 4);
part_type_alpha3(global.ember_part, 1, 1, 0);
part_type_color3(global.ember_part, 255, 0, 0);
part_type_life(global.ember_part, room_speed / 2, room_speed);
part_type_blend(global.ember_part, false);
global.burn_partemitter = part_emitter_create(global.over_partsys);
global.blessing_part = part_type_create();
part_type_sprite(global.blessing_part, spr_part_glow, 0, 0, 0);
part_type_scale(global.blessing_part, 0.2, 0.2);
part_type_size(global.blessing_part, 0.8, 1.4, 0, 0);
part_type_alpha3(global.blessing_part, 0, 0.7, 0);
part_type_color3(global.blessing_part, 16777215, 65535, 16777215);
part_type_direction(global.blessing_part, 80, 100, 0, 0);
part_type_life(global.blessing_part, room_speed * 1.5, room_speed * 3);
part_type_gravity(global.blessing_part, -0.05, 270);
global.blessing_partemitter = part_emitter_create(global.over_partsys);
global.arrowDead_part = part_type_create();
part_type_sprite(global.arrowDead_part, spr_arrow, 0, 0, 0);
part_type_scale(global.arrowDead_part, 1, 1);
part_type_size(global.arrowDead_part, 1, 1, 0, 0);
part_type_speed(global.arrowDead_part, 0, 0, 0, 0);
part_type_alpha2(global.arrowDead_part, 1, 0);
part_type_orientation(global.arrowDead_part, 300, 300, 0, 0, 0);
part_type_direction(global.arrowDead_part, 300, 300, 0, 0);
part_type_life(global.arrowDead_part, room_speed, room_speed * 2);
global.arrows_part = part_type_create();
part_type_sprite(global.arrows_part, spr_arrow, 0, 0, 0);
part_type_scale(global.arrows_part, 1, 1);
part_type_size(global.arrows_part, 1, 1, 0, 0);
part_type_speed(global.arrows_part, 20, 20, 0, 0);
part_type_alpha3(global.arrows_part, 1, 1, 0.5);
part_type_orientation(global.arrows_part, 310, 310, -1, 0, 0);
part_type_direction(global.arrows_part, 310, 310, -1, 0);
part_type_life(global.arrows_part, room_speed / 1.85, room_speed / 1.65);
part_type_death(global.arrows_part, 1, global.arrowDead_part);
global.arrows_partemitter = part_emitter_create(global.raidObject_partsys);
part_system_position(global.raidObject_partsys, 0, 0);
global.xprainpart_emitter = part_emitter_create(global.light_partsys);
global.bonanzapart_emitter = part_emitter_create(global.light_partsys);
global.heavenpower_emitter = part_emitter_create(global.light_partsys);
