extend = 0;
maxExtend = sprite_height;
c_dmgType[0] = 16777215;
c_dmgType[1] = 255;
c_dmgType[2] = 16776960;
c_dmgType[3] = 65535;
c_dmgType[4] = 16777215;
c_dmgType[5] = 65535;
c_dmgType[6] = 65535;
rewardedTalent = 0;
rewardedGems = 0;
damageDealtGrid = gml_Script_scr_ds_grid_create(ds_grid_width(global.combatStats1), ds_grid_height(global.combatStats1));
damageMitigatedGrid = gml_Script_scr_ds_grid_create(ds_grid_width(global.combatStats2), ds_grid_height(global.combatStats2));
ds_grid_copy(damageDealtGrid, global.combatStats1);
ds_grid_copy(damageMitigatedGrid, global.combatStats2);
totalCombatDamageDealt = ds_grid_get_sum(damageDealtGrid, 1, 0, 1, ds_grid_height(damageDealtGrid));
totalCombatDamageMitigated = ds_grid_get_sum(damageMitigatedGrid, 1, 0, 1, ds_grid_height(damageMitigatedGrid));
alarm[1] = 1;
alarm[0] = room_speed * 20;
