event_inherited();
bgSpd /= 4;
target = instance_nearest(x, y, obj_enemy);
armorReduction = 0;
hitList = gml_Script_scr_ds_list_create();
sprite = spr_arrow;
sprite_color = 16777215;
i_index = 0;
skipDmg = false;
hitCount = 0;
maxHitCount = 1;
image_speed = 0;
image_xscale = 2;
image_yscale = 2;
move_towards_point(x + 1, y + random_range(-0.02, 0.02), 40);
image_angle = direction;
gml_Script_scr_playsound(s_arrow1, 1, 1.2, 0.5);
alarm[0] = 1;
alarm[2] = room_speed * 2;
