move_snap(2, 2);
text = string(global.cmdPrefix) + "farm";
name = "Farm";
hp = 0;
depth = -100;
ini_open(string(global.platformDir) + "Village Data/Data.ini");
level = ini_read_real("Buildings", name + " Level", 1);
cost = ini_read_real("Buildings", name + " Cost", 1000);
oCost = ini_read_real("Buildings", name + " Original Cost", 1000);
cost2 = ini_read_real("Buildings", name + " Cost 2", 0);
oCost2 = ini_read_real("Buildings", name + " Original Cost 2", 0);
ini_close();
costText = gml_Script_scr_bigNumber(cost);
maxhp = 5;
oamount = 0;
amount = 0;
currentSlots = 0;
farmList = gml_Script_scr_ds_list_create();
global.farmingVP = (level / 10) + (global.farmerGuildLevel / 3);
